/**
* Platform Configuration for Reports
* Used to add platform details to CSV exports for official documentation.
*
* PRODUCTION CHECKLIST set these in your Vercel / server environment:
* PLATFORM_GSTIN actual company GSTIN (e.g. 29XXXXX1234F1Z5)
* PLATFORM_CIN Company Identification Number (e.g. U72900HR2023PTC000001)
* PLATFORM_PAN Company PAN (e.g. XXXCD1234F)
* PLATFORM_ADDRESS Registered office address
* PLATFORM_EMAIL Official support / legal email
* PLATFORM_PHONE Official phone number
* PLATFORM_WEBSITE Public website URL
*
* If any value is missing at runtime the export will contain a clearly-marked
* placeholder string so that generated reports are never silently invalid.
*/

function configValue(envKey: string, placeholder: string): string {
const val = process.env[envKey];
if (val?.trim()) return val.trim();
// In production, surface the missing-config problem loudly in every report
// rather than emitting a fake value that could be legally relied upon.
return `[MISSING: set ${envKey} env var ${placeholder}]`;
}

export const PLATFORM_CONFIG = {
name: "VyaparMedia",
legalName: "VYAPARMEDIA TECHNOLOGIES PRIVATE LIMITED",
address: configValue("PLATFORM_ADDRESS", "Registered office address"),
gstin: configValue("PLATFORM_GSTIN", "Company GSTIN"),
email: process.env.PLATFORM_EMAIL || "support@VyaparMedia.in",
phone: process.env.PLATFORM_PHONE || "+91-XXXXXXXXXX",
website: process.env.PLATFORM_WEBSITE || "https://VyaparMedia.in",
cin: configValue("PLATFORM_CIN", "Company Identification Number"),
pan: configValue("PLATFORM_PAN", "Company PAN"),
} as const;

export function getPlatformHeader(): string[] {
const { name, legalName, address, gstin, email, phone, website } = PLATFORM_CONFIG;
return [
`Platform: ${name}`,
`Legal Name: ${legalName}`,
`Address: ${address}`,
`GSTIN: ${gstin}`,
`Email: ${email}`,
`Phone: ${phone}`,
`Website: ${website}`,
`Generated: ${new Date().toISOString()}`,
];
}

export function getPlatformFooter(): string[] {
const { name, website, email } = PLATFORM_CONFIG;
return [
"",
`--- End of Report ---`,
`Generated by ${name}`,
`For queries: ${email} | ${website}`,
];
}
